[tools]
"cargo:tire" = "0.1.3"
kyverno = "1.19.0"
uv = "0.12.10"
sops = "3.13.3"
helm = "3.21.4"
kubectl = "1.37.0"
"pipx:slap-cli" = "1.15.0"

[tasks.build-docs]
dir = "docs"
run = "uv run mkdocs build"

[tasks.serve-docs]
dir = "docs"
run = "uv run mkdocs serve"
