# To be put in /home/argocd/cmp-server/config/plugin.yaml
# Read also https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#sidecar-plugin

apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: nyl
spec:
  # note: Plugin name in ArgoCD will be `nyl-v1`.
  version: v1

  discover:
    find:
      command:
        - sh
        - -c
        - find . -name nyl-project.yaml -o -name nyl-secrets.yml -o -name nyl-profiles.yaml

  init:
    command:
      - sh
      - -c
      - |
        nyl version >&2
        argocd-cmp-server version >&2

  generate:
    command:
      - sh
      - -c
      - nyl template .

  parameters: {}

  # If set to `true` then the plugin receives repository files with original file mode. Dangerous since the repository
  # might have executable files. Set to true only if you trust the CMP plugin authors.
  preserveFileMode: false
