[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = ["bcrypt>=4.2.0", "databind>=4.5.2", "filelock>=3.15.4", "jinja2>=3.1.4", "kubernetes>=30.1.0", "loguru>=0.7.2", "nr-stream>=1.1.5", "pyroscope-io>=0.8.11", "pyyaml>=6.0.1", "requests>=2.32.3", "rich>=13.7.0", "stablehash>=0.2.1,<0.3.0", "structured-templates>=0.1.1", "typer>=0.12.3", "typing-extensions>=4.12.2"]
description = "Advanced templating engine for Kubernetes and GitOps."
name = "nyl"
readme = "README.md"
requires-python = ">=3.11"
version = "0.10.5"

[[project.authors]]
email = "rosensteinniklas@gmail.com"
name = "Niklas Rosenstein"

[project.license]
text = "MIT"

[project.scripts]
nyl = "nyl.commands:main"

[tool.mypy]
enable_error_code = "ignore-without-code, possibly-undefined"
explicit_package_bases = true
mypy_path = ["src"]
namespace_packages = true
pretty = false
python_version = "${TIRE_MIN_PYTHON_VERSION}"
show_error_codes = true
show_error_context = true
strict = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
console_output_style = "count"
log_cli_level = "info"
verbosity_assertions = 2
verbosity_test_cases = 1

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.lint.isort]
forced-separate = ["test", "tests", "testing", "testsuite"]

[tool.slap.release]
pre-commit = "uv lock && git add uv.lock && slap changelog format --all --markdown > docs/content/changelog.md && git add docs/content/changelog.md"

[tool.uv]
dev-dependencies = ["kubernetes-stubs>=22.6.0.post1", "mypy>=1.13.0", "pytest>=8.2.2", "pytest-xdist>=3.8.0", "ruff>=0.7.2", "types-pyyaml>=6.0.12.20240311", "types-requests>=2.32.0.20240712"]
