SOPS_AGE_KEY: ENC[AES256_GCM,data:tlEyMd6e8GNsZyogYXUTzEqtgAOUkGkgbE7kqkepNct/uqoe+R34/1aGj00IItC8ZazPvZp47S4c3sr7mP7lZ4ji6wiCi6n3eME=,iv:DtoexO7+KbO7Mgue3PP6yjBZC9ni6J2fKbRcCIlJzu8=,tag:LVNQ5GDuUjdm29xys49dNg==,type:str]
ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:UYfk+Rs54r8=,iv:zWFYTQc4TTRBhi0lnA9xIzZzS58CGchRRpP8m/Wpd1U=,tag:85il8J3C/I+UjhjGfQsrig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13e8qcv3hku3pw5nufw6p7m30zzl9rkgns7qmpc6p2laacddvgqlq6fh4t4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc1pRNXVYRGxoVWpLNkJB
            QzcxSTZoZGhGMFBRY29GOUdHdkVNQTNlSFRnCkdNRXJMUzByV2w3LzRYeDdha2VH
            Y3JOWEJ4Z2J2TVZqZzZkdG1VMkRaU2sKLS0tIHpMZS9aeDNsUG9NbVlTUnQ5VG1M
            RndMcU56RFQyVDdvTVljbllQeWJJbGsK61K7dUfaOE1evbuZSKib9ayF3CZzJc0l
            TK6lOwUQ/nns8zV0r01480QSSgKtegAfkbXVf9YpGDS/rodxJqO4lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T00:50:55Z"
    mac: ENC[AES256_GCM,data:WZvAVDxY3z5OsTYhAzOIhLJESfLox9USD6gRmMLvAmIZdOiCRBgpL4xTQwA36/biGswWsMrg3CiEV7+vKuKNsr+ko3qyyzNp8FAfet4DOjZqF5lgh6FptMpYxYcby2t2Lcy9wy4QyjLdspviHO98k6rNPTUByFFipEUriYoQzrw=,iv:Jyd7knp2qL5Ifbt8T333wwxKHmoI+CyxOb/r9J6XcTg=,tag:ko6/5Ro0SQwjB01qRDXwYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
