#
# This is an example Kubernetes manifest that can be applied with Nyl to deploy ArgoCD with Nyl as a Config Management
# Plugin.
#

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-nyl-env
  namespace: argocd
type: Opaque
stringData:
  SOPS_AGE_KEY: ${{ secrets.get("SOPS_AGE_KEY") }}

---
apiVersion: inline.nyl.io/v1
kind: HelmChart
release:
  name: argocd
  namespace: argocd
chart:
  # Explore the chart at https://artifacthub.io/packages/helm/argo/argo-cd
  repository: https://argoproj.github.io/argo-helm
  name: argo-cd
  version: "7.4.3"
values:
  dex:
    enabled: false
  repoServer:
    extraContainers:
      - name: nyl-v1
        image: ghcr.io/niklasrosenstein/nyl/argocd-cmp:256fb1659c7f3057b10d0b5c27c43ffcc20b23ae
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: cmp-tmp
        envFrom:
          - secretRef:
              name: argocd-nyl-env
    volumes:
      - name: cmp-tmp
        emptyDir: {}

# Self-manage ArgoCD with Nyl and this specific repository.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NiklasRosenstein/nyl.git
    targetRevision: nr/argocd-with-nyl-sops
    path: argocd-with-nyl
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
